### ISSUE TITLE
ext_emconf not updated to 0.3.2

### ISSUE THREAD

**Issue by RonaldKools** [codemonkey1988/be-google-auth#10]
When installing this plugin it still says 0.3.1 in Typo, even though it is 0.3.2. 

https://github.com/codemonkey1988/be-google-auth/blob/6057145a4147b690e608455ce6355d64dc675d96/ext_emconf.php#L11

**Comment by codemonkey1988** [comment]
Hey thanks for this hit.

Yeah, I totally forgot to update the emconf file. Will update it properly and release a new version so that it's correct.

**Comment by codemonkey1988** [comment]
This is fixed now. Please use version 0.3.3
