### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by IsikAkgun** [codemonkey1988/be-google-auth#6]
After i connected with my company google account, and presses Login, I still remain on the same page. 
Even if I edit the address to /typo3 i still landing on the login screen. 
There is no errormessage in the console.

**Comment by codemonkey1988** [comment]
This was an issue with TYPO3 v9. Is is fixed in commit https://github.com/codemonkey1988/be-google-auth/commit/dcbd1daa17a2dde8ca95c9e0b8d6c6bb9b1950ea
